import type { Metadata } from 'next';
import './globals.css';
import ThemeProviderWrapper from '../components/theme/theme-provider';

export const metadata: Metadata = {
  title: 'ESports-LAN',
  description: 'Generated by Xaptured',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
      </body>
    </html>
  );
}
